CREATE DATABASE IF NOT EXISTS houseMateDB;

USE houseMateDB;


CREATE TABLE IF NOT EXISTS users(
  id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(200) UNIQUE NOT NULL,
  emailAddress VARCHAR(200) UNIQUE NOT NULL,
  PRIMARY KEY(id)
);

ALTER TABLE users
  ADD auth VARCHAR(200) AFTER emailAddress;

ALTER TABLE users
  ADD password VARCHAR(200) AFTER auth;

